# Generated by Django 5.0.6 on 2024-06-30 12:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staircases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('arriving_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staircase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitor', to='staircases.staircase')),
            ],
        ),
    ]
