# Generated by Django 5.0.6 on 2024-07-02 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['-arriving_time']},
        ),
    ]
