# Generated by Django 5.0.6 on 2024-07-04 17:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_code', models.CharField(max_length=10)),
                ('work_reason', models.CharField(max_length=500)),
                ('contractor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contractor_number', models.CharField(blank=True, max_length=15, null=True)),
                ('expected_arriving_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('arriving_time', models.DateTimeField(blank=True, null=True)),
                ('leaving_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_the_building', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='company.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
