# Generated by Django 5.0.6 on 2024-07-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        ('staircases', '0002_alter_staircase_options'),
        ('work_type', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='responsible_worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='workers.worker'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='staircase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='staircases.staircase'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contractor', to='work_type.worktype'),
        ),
    ]
