# Generated by Django 5.0.6 on 2024-07-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staircases', '0002_alter_staircase_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('telephone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('staircase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker', to='staircases.staircase')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
